server:
  port: 6001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vns?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhx.vns.backend.dao

# 显示sql
logging:
  level:
    com:
      xhx:
        vns:
          backend:
            dao:  debug
