package com.xhx.vns.backend.pojo;

public class Architecture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_name
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String architectureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_longitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long architectureLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_latitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long architectureLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Byte architectureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_desc
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String architectureDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.ID
     *
     * @return the value of architecture.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.ID
     *
     * @param id the value for architecture.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_name
     *
     * @return the value of architecture.architecture_name
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArchitectureName() {
        return architectureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_name
     *
     * @param architectureName the value for architecture.architecture_name
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArchitectureName(String architectureName) {
        this.architectureName = architectureName == null ? null : architectureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_longitude
     *
     * @return the value of architecture.architecture_longitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getArchitectureLongitude() {
        return architectureLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_longitude
     *
     * @param architectureLongitude the value for architecture.architecture_longitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArchitectureLongitude(Long architectureLongitude) {
        this.architectureLongitude = architectureLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_latitude
     *
     * @return the value of architecture.architecture_latitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getArchitectureLatitude() {
        return architectureLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_latitude
     *
     * @param architectureLatitude the value for architecture.architecture_latitude
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArchitectureLatitude(Long architectureLatitude) {
        this.architectureLatitude = architectureLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_status
     *
     * @return the value of architecture.architecture_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Byte getArchitectureStatus() {
        return architectureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_status
     *
     * @param architectureStatus the value for architecture.architecture_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArchitectureStatus(Byte architectureStatus) {
        this.architectureStatus = architectureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg1
     *
     * @return the value of architecture.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg1() {
        return arg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg1
     *
     * @param arg1 the value for architecture.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg1(String arg1) {
        this.arg1 = arg1 == null ? null : arg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg2
     *
     * @return the value of architecture.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg2() {
        return arg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg2
     *
     * @param arg2 the value for architecture.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg2(String arg2) {
        this.arg2 = arg2 == null ? null : arg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg3
     *
     * @return the value of architecture.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg3() {
        return arg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg3
     *
     * @param arg3 the value for architecture.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg3(String arg3) {
        this.arg3 = arg3 == null ? null : arg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_desc
     *
     * @return the value of architecture.architecture_desc
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArchitectureDesc() {
        return architectureDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_desc
     *
     * @param architectureDesc the value for architecture.architecture_desc
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArchitectureDesc(String architectureDesc) {
        this.architectureDesc = architectureDesc == null ? null : architectureDesc.trim();
    }
}