package com.xhx.vns.backend.pojo;

import java.math.BigDecimal;

public class Architecture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.ID
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_name
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String architectureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_longitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private BigDecimal architectureLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_latitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private BigDecimal architectureLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_status
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private Byte architectureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_iconPath
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String markIconpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_labelContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String markLabelcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_calloutContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String markCalloutcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_width
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private Integer markWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_height
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private Integer markHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.mark_infoContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String markInfocontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg1
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String arg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg2
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String arg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.arg3
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String arg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column architecture.architecture_desc
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    private String architectureDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.ID
     *
     * @return the value of architecture.ID
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.ID
     *
     * @param id the value for architecture.ID
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_name
     *
     * @return the value of architecture.architecture_name
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getArchitectureName() {
        return architectureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_name
     *
     * @param architectureName the value for architecture.architecture_name
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArchitectureName(String architectureName) {
        this.architectureName = architectureName == null ? null : architectureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_longitude
     *
     * @return the value of architecture.architecture_longitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public BigDecimal getArchitectureLongitude() {
        return architectureLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_longitude
     *
     * @param architectureLongitude the value for architecture.architecture_longitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArchitectureLongitude(BigDecimal architectureLongitude) {
        this.architectureLongitude = architectureLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_latitude
     *
     * @return the value of architecture.architecture_latitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public BigDecimal getArchitectureLatitude() {
        return architectureLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_latitude
     *
     * @param architectureLatitude the value for architecture.architecture_latitude
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArchitectureLatitude(BigDecimal architectureLatitude) {
        this.architectureLatitude = architectureLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_status
     *
     * @return the value of architecture.architecture_status
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public Byte getArchitectureStatus() {
        return architectureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_status
     *
     * @param architectureStatus the value for architecture.architecture_status
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArchitectureStatus(Byte architectureStatus) {
        this.architectureStatus = architectureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_iconPath
     *
     * @return the value of architecture.mark_iconPath
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getMarkIconpath() {
        return markIconpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_iconPath
     *
     * @param markIconpath the value for architecture.mark_iconPath
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkIconpath(String markIconpath) {
        this.markIconpath = markIconpath == null ? null : markIconpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_labelContent
     *
     * @return the value of architecture.mark_labelContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getMarkLabelcontent() {
        return markLabelcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_labelContent
     *
     * @param markLabelcontent the value for architecture.mark_labelContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkLabelcontent(String markLabelcontent) {
        this.markLabelcontent = markLabelcontent == null ? null : markLabelcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_calloutContent
     *
     * @return the value of architecture.mark_calloutContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getMarkCalloutcontent() {
        return markCalloutcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_calloutContent
     *
     * @param markCalloutcontent the value for architecture.mark_calloutContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkCalloutcontent(String markCalloutcontent) {
        this.markCalloutcontent = markCalloutcontent == null ? null : markCalloutcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_width
     *
     * @return the value of architecture.mark_width
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public Integer getMarkWidth() {
        return markWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_width
     *
     * @param markWidth the value for architecture.mark_width
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkWidth(Integer markWidth) {
        this.markWidth = markWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_height
     *
     * @return the value of architecture.mark_height
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public Integer getMarkHeight() {
        return markHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_height
     *
     * @param markHeight the value for architecture.mark_height
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkHeight(Integer markHeight) {
        this.markHeight = markHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.mark_infoContent
     *
     * @return the value of architecture.mark_infoContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getMarkInfocontent() {
        return markInfocontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.mark_infoContent
     *
     * @param markInfocontent the value for architecture.mark_infoContent
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setMarkInfocontent(String markInfocontent) {
        this.markInfocontent = markInfocontent == null ? null : markInfocontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg1
     *
     * @return the value of architecture.arg1
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getArg1() {
        return arg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg1
     *
     * @param arg1 the value for architecture.arg1
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArg1(String arg1) {
        this.arg1 = arg1 == null ? null : arg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg2
     *
     * @return the value of architecture.arg2
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getArg2() {
        return arg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg2
     *
     * @param arg2 the value for architecture.arg2
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArg2(String arg2) {
        this.arg2 = arg2 == null ? null : arg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.arg3
     *
     * @return the value of architecture.arg3
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getArg3() {
        return arg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.arg3
     *
     * @param arg3 the value for architecture.arg3
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArg3(String arg3) {
        this.arg3 = arg3 == null ? null : arg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column architecture.architecture_desc
     *
     * @return the value of architecture.architecture_desc
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public String getArchitectureDesc() {
        return architectureDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column architecture.architecture_desc
     *
     * @param architectureDesc the value for architecture.architecture_desc
     *
     * @mbggenerated Wed May 09 11:13:09 CST 2018
     */
    public void setArchitectureDesc(String architectureDesc) {
        this.architectureDesc = architectureDesc == null ? null : architectureDesc.trim();
    }
}