package com.xhx.vns.backend.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_architecture_ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long commentArchitectureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_author
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long commentAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_target
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long commentTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_date
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Date commentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_date_gmt
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Date commentDateGmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Byte commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_likenum
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Integer commentLikenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_parent
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private Long commentParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    private String arg3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ID
     *
     * @return the value of comment.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ID
     *
     * @param id the value for comment.ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_architecture_ID
     *
     * @return the value of comment.comment_architecture_ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getCommentArchitectureId() {
        return commentArchitectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_architecture_ID
     *
     * @param commentArchitectureId the value for comment.comment_architecture_ID
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentArchitectureId(Long commentArchitectureId) {
        this.commentArchitectureId = commentArchitectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_author
     *
     * @return the value of comment.comment_author
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getCommentAuthor() {
        return commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_author
     *
     * @param commentAuthor the value for comment.comment_author
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentAuthor(Long commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_target
     *
     * @return the value of comment.comment_target
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getCommentTarget() {
        return commentTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_target
     *
     * @param commentTarget the value for comment.comment_target
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentTarget(Long commentTarget) {
        this.commentTarget = commentTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_date
     *
     * @return the value of comment.comment_date
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_date
     *
     * @param commentDate the value for comment.comment_date
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_date_gmt
     *
     * @return the value of comment.comment_date_gmt
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Date getCommentDateGmt() {
        return commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_date_gmt
     *
     * @param commentDateGmt the value for comment.comment_date_gmt
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentDateGmt(Date commentDateGmt) {
        this.commentDateGmt = commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_status
     *
     * @return the value of comment.comment_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Byte getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_status
     *
     * @param commentStatus the value for comment.comment_status
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentStatus(Byte commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_likenum
     *
     * @return the value of comment.comment_likenum
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Integer getCommentLikenum() {
        return commentLikenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_likenum
     *
     * @param commentLikenum the value for comment.comment_likenum
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentLikenum(Integer commentLikenum) {
        this.commentLikenum = commentLikenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_parent
     *
     * @return the value of comment.comment_parent
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public Long getCommentParent() {
        return commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_parent
     *
     * @param commentParent the value for comment.comment_parent
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setCommentParent(Long commentParent) {
        this.commentParent = commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.arg1
     *
     * @return the value of comment.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg1() {
        return arg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.arg1
     *
     * @param arg1 the value for comment.arg1
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg1(String arg1) {
        this.arg1 = arg1 == null ? null : arg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.arg2
     *
     * @return the value of comment.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg2() {
        return arg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.arg2
     *
     * @param arg2 the value for comment.arg2
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg2(String arg2) {
        this.arg2 = arg2 == null ? null : arg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.arg3
     *
     * @return the value of comment.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public String getArg3() {
        return arg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.arg3
     *
     * @param arg3 the value for comment.arg3
     *
     * @mbggenerated Thu Apr 12 11:22:23 CST 2018
     */
    public void setArg3(String arg3) {
        this.arg3 = arg3 == null ? null : arg3.trim();
    }
}